sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t niktaw/react-test -f ./client/Dockerfile.dev ./client

scipt:
  - docker run -e CI=true niktaw/react-test npm test

after_success:
  - docker build -t niktaw/blog-multi-client ./client
  - docker build -t niktaw/blog-multi-nginx ./nginx
  - docker build -t niktaw/blog-multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push niktaw/blog-multi-client
  - docker push niktaw/blog-multi-nginx
  - docker push niktaw/blog-multi-server

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env:  MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-684307455729
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
